#mybatis:
#  #指sql语句在配置文件中的情况
#  mapper-locations: classpath*:/mappers/*Mapper.xml
#  configuration:
#    mapUnderscoreToCamelCase: true
#spring:
#  datasource:
#    dynamic:
#      #dao没有指定访问哪个数据源，指定默认的数据源
#      primary: mysql
#      #是否是严格模式，严格模式指dao没有指定数据源，就报错。 非严格模式允许dao不配置数据源，会启动默认数据源进行连接
#      strict: false
#      datasource:
#        #定义了三个数据源，mybatis(mysql)，ck(clickhouse),hbase(hbase)
#        mysql:
#          url: jdbc:mysql://hadoop101:3306/api_service?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#          username: root
#          password: "root"
#          driver-class-name: com.mysql.jdbc.Driver